version: "2"
run:
  go: "1.25"
  tests: false
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - dupl
    - goconst
    - gosec
    - govet
    - importas
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - unconvert
    - whitespace
  settings:
    importas:
      alias:
        - pkg: k8s.io/api/core/v1
          alias: corev1
        - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
          alias: apiextensionsv1
        - pkg: k8s.io/api/apps/v1
          alias: appsv1
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
        - pkg: k8s.io/apimachinery/pkg/util/runtime
          alias: utilruntime
        - pkg: sigs.k8s.io/controller-runtime/pkg/client
          alias: runtimeclient
        - pkg: k8s.io/apimachinery/pkg/util/errors
          alias: kerrors
        - pkg: k8s.io/client-go/kubernetes/scheme
          alias: clientgoscheme
        - pkg: github.com/rancher/gke-operator/pkg/apis/gke.cattle.io/v1
          alias: gkev1
        - pkg: github.com/rancher/gke-operator/pkg/generated/controllers/gke.cattle.io/v1
          alias: gkecontrollers
        - pkg: google.golang.org/api/container/v1
          alias: gkeapi
      no-unaliased: true
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        path: mock(\w+)/doc.go$
        text: 'var-naming: don''t use an underscore in package name'
      - linters:                                           
          - revive
        path: utils/
        text: 'var-naming: avoid meaningless package names' 
    paths:
      - zz_generated_*
      - pkg/generated
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - zz_generated_*
      - pkg/generated
      - third_party$
      - builtin$
      - examples$
