run:
  timeout: 5m
  go: "1.24"
  tests: false
  allow-parallel-runners: true

output:
  formats:
    - format: github-actions

linters:
  disable-all: true
  enable:
    - dupl # check duplicated code
    - goconst # check strings that can turn into constants
    - gofmt # check fmt
    - goimports # check imports
    - gosec # check for security problems
    - govet # check vet
    - importas # check consistent import aliasing
    - ineffassign # check ineffectual assignments
    - misspell # check for misspelled English words
    - nakedret # check naked returns in functions
    - prealloc # check preallocated slice declarations
    - revive # replacement for golint
    - unconvert # check redundant type conversions
    - whitespace # check for trailing whitespace and tabs
linters-settings:
  revive:
    rules:
      # The following rules are recommended https://github.com/mgechev/revive#recommended-configuration
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
  importas:
    no-unaliased: true
    alias:
      # Kubernetes
      - pkg: k8s.io/api/core/v1
        alias: corev1
      - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
        alias: apiextensionsv1
      - pkg: k8s.io/api/apps/v1
        alias: appsv1
      - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
        alias: metav1
      - pkg: k8s.io/apimachinery/pkg/util/runtime
        alias: utilruntime
      - pkg: sigs.k8s.io/controller-runtime/pkg/client
        alias: runtimeclient
      - pkg: k8s.io/apimachinery/pkg/util/errors
        alias: kerrors
      - pkg: k8s.io/client-go/kubernetes/scheme
        alias: clientgoscheme
      # Rancher GKE operator
      - pkg: github.com/rancher/gke-operator/pkg/apis/gke.cattle.io/v1
        alias: gkev1
      - pkg: github.com/rancher/gke-operator/pkg/generated/controllers/gke.cattle.io/v1
        alias: gkecontrollers
      # Golang API
      - pkg: google.golang.org/api/container/v1
        alias: gkeapi
issues:
  exclude-rules:
  - linters:
    - revive
    text: "var-naming: don't use an underscore in package name"
    path: 'mock(\w+)/doc.go$'
  exclude-dirs:
    - pkg/generated
  exclude-files:
    - "zz_generated_*"