#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p dist/artifacts
cp bin/gke-operator dist/artifacts/gke-operator-linux${SUFFIX}
for i in bin/gke-operator-*; do
    if [ -e "$i" ]; then
          cp $i dist/artifacts
    fi
done

./scripts/package-helm