//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2019 Wrangler Sample Controller Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by main. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CMEKConfig) DeepCopyInto(out *CMEKConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CMEKConfig.
func (in *CMEKConfig) DeepCopy() *CMEKConfig {
	if in == nil {
		return nil
	}
	out := new(CMEKConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKEAutopilotConfig) DeepCopyInto(out *GKEAutopilotConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKEAutopilotConfig.
func (in *GKEAutopilotConfig) DeepCopy() *GKEAutopilotConfig {
	if in == nil {
		return nil
	}
	out := new(GKEAutopilotConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKEBinaryAuthorization) DeepCopyInto(out *GKEBinaryAuthorization) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKEBinaryAuthorization.
func (in *GKEBinaryAuthorization) DeepCopy() *GKEBinaryAuthorization {
	if in == nil {
		return nil
	}
	out := new(GKEBinaryAuthorization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKECidrBlock) DeepCopyInto(out *GKECidrBlock) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKECidrBlock.
func (in *GKECidrBlock) DeepCopy() *GKECidrBlock {
	if in == nil {
		return nil
	}
	out := new(GKECidrBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKEClientCertificateConfig) DeepCopyInto(out *GKEClientCertificateConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKEClientCertificateConfig.
func (in *GKEClientCertificateConfig) DeepCopy() *GKEClientCertificateConfig {
	if in == nil {
		return nil
	}
	out := new(GKEClientCertificateConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKEClusterAddons) DeepCopyInto(out *GKEClusterAddons) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKEClusterAddons.
func (in *GKEClusterAddons) DeepCopy() *GKEClusterAddons {
	if in == nil {
		return nil
	}
	out := new(GKEClusterAddons)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKEClusterConfig) DeepCopyInto(out *GKEClusterConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKEClusterConfig.
func (in *GKEClusterConfig) DeepCopy() *GKEClusterConfig {
	if in == nil {
		return nil
	}
	out := new(GKEClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GKEClusterConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKEClusterConfigList) DeepCopyInto(out *GKEClusterConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GKEClusterConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKEClusterConfigList.
func (in *GKEClusterConfigList) DeepCopy() *GKEClusterConfigList {
	if in == nil {
		return nil
	}
	out := new(GKEClusterConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GKEClusterConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKEClusterConfigSpec) DeepCopyInto(out *GKEClusterConfigSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.EnableKubernetesAlpha != nil {
		in, out := &in.EnableKubernetesAlpha, &out.EnableKubernetesAlpha
		*out = new(bool)
		**out = **in
	}
	if in.ClusterAddons != nil {
		in, out := &in.ClusterAddons, &out.ClusterAddons
		*out = new(GKEClusterAddons)
		**out = **in
	}
	if in.ClusterIpv4CidrBlock != nil {
		in, out := &in.ClusterIpv4CidrBlock, &out.ClusterIpv4CidrBlock
		*out = new(string)
		**out = **in
	}
	if in.KubernetesVersion != nil {
		in, out := &in.KubernetesVersion, &out.KubernetesVersion
		*out = new(string)
		**out = **in
	}
	if in.LoggingService != nil {
		in, out := &in.LoggingService, &out.LoggingService
		*out = new(string)
		**out = **in
	}
	if in.MonitoringService != nil {
		in, out := &in.MonitoringService, &out.MonitoringService
		*out = new(string)
		**out = **in
	}
	if in.NodePools != nil {
		in, out := &in.NodePools, &out.NodePools
		*out = make([]GKENodePoolConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(string)
		**out = **in
	}
	if in.Subnetwork != nil {
		in, out := &in.Subnetwork, &out.Subnetwork
		*out = new(string)
		**out = **in
	}
	if in.NetworkPolicyEnabled != nil {
		in, out := &in.NetworkPolicyEnabled, &out.NetworkPolicyEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PrivateClusterConfig != nil {
		in, out := &in.PrivateClusterConfig, &out.PrivateClusterConfig
		*out = new(GKEPrivateClusterConfig)
		**out = **in
	}
	if in.IPAllocationPolicy != nil {
		in, out := &in.IPAllocationPolicy, &out.IPAllocationPolicy
		*out = new(GKEIPAllocationPolicy)
		**out = **in
	}
	if in.MasterAuthorizedNetworksConfig != nil {
		in, out := &in.MasterAuthorizedNetworksConfig, &out.MasterAuthorizedNetworksConfig
		*out = new(GKEMasterAuthorizedNetworksConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Locations != nil {
		in, out := &in.Locations, &out.Locations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MaintenanceWindow != nil {
		in, out := &in.MaintenanceWindow, &out.MaintenanceWindow
		*out = new(string)
		**out = **in
	}
	if in.AutopilotConfig != nil {
		in, out := &in.AutopilotConfig, &out.AutopilotConfig
		*out = new(GKEAutopilotConfig)
		**out = **in
	}
	if in.CustomerManagedEncryptionKey != nil {
		in, out := &in.CustomerManagedEncryptionKey, &out.CustomerManagedEncryptionKey
		*out = new(CMEKConfig)
		**out = **in
	}
	if in.DatabaseEncryption != nil {
		in, out := &in.DatabaseEncryption, &out.DatabaseEncryption
		*out = new(GKEDatabaseEncryption)
		**out = **in
	}
	if in.BinaryAuthorization != nil {
		in, out := &in.BinaryAuthorization, &out.BinaryAuthorization
		*out = new(GKEBinaryAuthorization)
		**out = **in
	}
	if in.ShieldedNodes != nil {
		in, out := &in.ShieldedNodes, &out.ShieldedNodes
		*out = new(GKEShieldedNodes)
		**out = **in
	}
	if in.WorkloadIdentityConfig != nil {
		in, out := &in.WorkloadIdentityConfig, &out.WorkloadIdentityConfig
		*out = new(GKEWorkloadIdentityConfig)
		**out = **in
	}
	if in.LegacyAbac != nil {
		in, out := &in.LegacyAbac, &out.LegacyAbac
		*out = new(GKELegacyAbac)
		**out = **in
	}
	if in.MasterAuth != nil {
		in, out := &in.MasterAuth, &out.MasterAuth
		*out = new(GKEMasterAuth)
		(*in).DeepCopyInto(*out)
	}
	if in.IntraNodeVisibilityConfig != nil {
		in, out := &in.IntraNodeVisibilityConfig, &out.IntraNodeVisibilityConfig
		*out = new(GKEIntraNodeVisibilityConfig)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKEClusterConfigSpec.
func (in *GKEClusterConfigSpec) DeepCopy() *GKEClusterConfigSpec {
	if in == nil {
		return nil
	}
	out := new(GKEClusterConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKEClusterConfigStatus) DeepCopyInto(out *GKEClusterConfigStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKEClusterConfigStatus.
func (in *GKEClusterConfigStatus) DeepCopy() *GKEClusterConfigStatus {
	if in == nil {
		return nil
	}
	out := new(GKEClusterConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKEDatabaseEncryption) DeepCopyInto(out *GKEDatabaseEncryption) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKEDatabaseEncryption.
func (in *GKEDatabaseEncryption) DeepCopy() *GKEDatabaseEncryption {
	if in == nil {
		return nil
	}
	out := new(GKEDatabaseEncryption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKEIPAllocationPolicy) DeepCopyInto(out *GKEIPAllocationPolicy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKEIPAllocationPolicy.
func (in *GKEIPAllocationPolicy) DeepCopy() *GKEIPAllocationPolicy {
	if in == nil {
		return nil
	}
	out := new(GKEIPAllocationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKEIntraNodeVisibilityConfig) DeepCopyInto(out *GKEIntraNodeVisibilityConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKEIntraNodeVisibilityConfig.
func (in *GKEIntraNodeVisibilityConfig) DeepCopy() *GKEIntraNodeVisibilityConfig {
	if in == nil {
		return nil
	}
	out := new(GKEIntraNodeVisibilityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKELegacyAbac) DeepCopyInto(out *GKELegacyAbac) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKELegacyAbac.
func (in *GKELegacyAbac) DeepCopy() *GKELegacyAbac {
	if in == nil {
		return nil
	}
	out := new(GKELegacyAbac)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKEMasterAuth) DeepCopyInto(out *GKEMasterAuth) {
	*out = *in
	if in.ClientCertificateConfig != nil {
		in, out := &in.ClientCertificateConfig, &out.ClientCertificateConfig
		*out = new(GKEClientCertificateConfig)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKEMasterAuth.
func (in *GKEMasterAuth) DeepCopy() *GKEMasterAuth {
	if in == nil {
		return nil
	}
	out := new(GKEMasterAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKEMasterAuthorizedNetworksConfig) DeepCopyInto(out *GKEMasterAuthorizedNetworksConfig) {
	*out = *in
	if in.CidrBlocks != nil {
		in, out := &in.CidrBlocks, &out.CidrBlocks
		*out = make([]*GKECidrBlock, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(GKECidrBlock)
				**out = **in
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKEMasterAuthorizedNetworksConfig.
func (in *GKEMasterAuthorizedNetworksConfig) DeepCopy() *GKEMasterAuthorizedNetworksConfig {
	if in == nil {
		return nil
	}
	out := new(GKEMasterAuthorizedNetworksConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKENodeConfig) DeepCopyInto(out *GKENodeConfig) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.OauthScopes != nil {
		in, out := &in.OauthScopes, &out.OauthScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Taints != nil {
		in, out := &in.Taints, &out.Taints
		*out = make([]GKENodeTaintConfig, len(*in))
		copy(*out, *in)
	}
	if in.ShieldedInstanceConfig != nil {
		in, out := &in.ShieldedInstanceConfig, &out.ShieldedInstanceConfig
		*out = new(GKEShieldedInstanceConfig)
		**out = **in
	}
	if in.WorkloadMetadataConfig != nil {
		in, out := &in.WorkloadMetadataConfig, &out.WorkloadMetadataConfig
		*out = new(GKEWorkloadMetadataConfig)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKENodeConfig.
func (in *GKENodeConfig) DeepCopy() *GKENodeConfig {
	if in == nil {
		return nil
	}
	out := new(GKENodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKENodePoolAutoscaling) DeepCopyInto(out *GKENodePoolAutoscaling) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKENodePoolAutoscaling.
func (in *GKENodePoolAutoscaling) DeepCopy() *GKENodePoolAutoscaling {
	if in == nil {
		return nil
	}
	out := new(GKENodePoolAutoscaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKENodePoolConfig) DeepCopyInto(out *GKENodePoolConfig) {
	*out = *in
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(GKENodePoolAutoscaling)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(GKENodeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.InitialNodeCount != nil {
		in, out := &in.InitialNodeCount, &out.InitialNodeCount
		*out = new(int64)
		**out = **in
	}
	if in.MaxPodsConstraint != nil {
		in, out := &in.MaxPodsConstraint, &out.MaxPodsConstraint
		*out = new(int64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.Management != nil {
		in, out := &in.Management, &out.Management
		*out = new(GKENodePoolManagement)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKENodePoolConfig.
func (in *GKENodePoolConfig) DeepCopy() *GKENodePoolConfig {
	if in == nil {
		return nil
	}
	out := new(GKENodePoolConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKENodePoolManagement) DeepCopyInto(out *GKENodePoolManagement) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKENodePoolManagement.
func (in *GKENodePoolManagement) DeepCopy() *GKENodePoolManagement {
	if in == nil {
		return nil
	}
	out := new(GKENodePoolManagement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKENodeTaintConfig) DeepCopyInto(out *GKENodeTaintConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKENodeTaintConfig.
func (in *GKENodeTaintConfig) DeepCopy() *GKENodeTaintConfig {
	if in == nil {
		return nil
	}
	out := new(GKENodeTaintConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKEPrivateClusterConfig) DeepCopyInto(out *GKEPrivateClusterConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKEPrivateClusterConfig.
func (in *GKEPrivateClusterConfig) DeepCopy() *GKEPrivateClusterConfig {
	if in == nil {
		return nil
	}
	out := new(GKEPrivateClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKEShieldedInstanceConfig) DeepCopyInto(out *GKEShieldedInstanceConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKEShieldedInstanceConfig.
func (in *GKEShieldedInstanceConfig) DeepCopy() *GKEShieldedInstanceConfig {
	if in == nil {
		return nil
	}
	out := new(GKEShieldedInstanceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKEShieldedNodes) DeepCopyInto(out *GKEShieldedNodes) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKEShieldedNodes.
func (in *GKEShieldedNodes) DeepCopy() *GKEShieldedNodes {
	if in == nil {
		return nil
	}
	out := new(GKEShieldedNodes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKEWorkloadIdentityConfig) DeepCopyInto(out *GKEWorkloadIdentityConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKEWorkloadIdentityConfig.
func (in *GKEWorkloadIdentityConfig) DeepCopy() *GKEWorkloadIdentityConfig {
	if in == nil {
		return nil
	}
	out := new(GKEWorkloadIdentityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKEWorkloadMetadataConfig) DeepCopyInto(out *GKEWorkloadMetadataConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKEWorkloadMetadataConfig.
func (in *GKEWorkloadMetadataConfig) DeepCopy() *GKEWorkloadMetadataConfig {
	if in == nil {
		return nil
	}
	out := new(GKEWorkloadMetadataConfig)
	in.DeepCopyInto(out)
	return out
}
