name: Go API Diff
on: 
  pull_request:
jobs:
  go-apidiff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v6
      with:
        go-version: 1.24.9
    - name: Generate API diff
      run: make apidiff
