name: Unit tests
on:
  pull_request:
  push:
    branches: [ "main", "release-v*" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.24.9
    - name: Run tests
      run: |
        make test
